# site settings
title: Fundação Cidadania Inteligente
email: info@cidadaniainteligente.org
description: "Usamos a tecnologia para tornar a democracia mais transparente e participativa; trabalhamos para compartilhar o poder de poucos para muitos."
baseurl: //cidadaniainteligente.org
basedomain: cidadaniainteligente.org
analytics: 'UA-31247996-3'
jquery_version: "2.1.3"

# build settings
markdown: kramdown
permalink: pretty

collections:
  rockstars:
    output: true
  projects:
    output: true
  board_members:
    output: true
